services: 

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    network_mode: host
    environment:
      - WEBPASSWORD=changeme
      - TZ=Europe/London
      - DNSMASQ_LISTENING=all
    volumes:
      - /mnt/nvme/pihole/etc:/etc/pihole
      - /mnt/nvme/pihole/dnsmasq:/etc/dnsmasq.d



